### ISSUE TITLE
LinkPicker data binding in the backend

### ISSUE THREAD

**Issue by FDBenevides** [skybrud/Skybrud.LinkPicker#6]
Hi @abjerner ,

I was trying to reuse your LinkPicker editor in a custom view but then when the data is sent to the backend to be saved, the data isn't correctly 'binded' for the 'LinkPickerList' object.
I've confirmed that the data is being passed on the Http Post to the backend and I've also confirmed that the "Title" property is correctly set, but the 'LinkPickerItem[] Items' isn't.

In the example above, "My Title" is correctly set in the backend, but the item array is shown as an empty LinkPickerItem[]:
```
"title": "My Title",
"items": [{
	"id": 1061,
	"name": "history",
	"url": "http://example.dev/history/",
	"target": "_self",
	"mode": "content"
}],
"count": 1
```

Can you help me to understand why this is happening?

PS: The functionality in the backoffice is working as expected :)

Thank you very much.
Best Regards

**Comment by abjerner** [comment]
@FDBenevides I think I may need some more information in order to help you. For instance, how do you try to convert the JSON back to an instance of `LinkPickerList`?

**Comment by FDBenevides** [comment]
Sure @abjerner :)

I can explain you my scenario :)

I have a `public class RequestApiController : UmbracoAuthorizedJsonController` with a public method  `PostSave (Request request)`. 
My 'Request' class has a Property `public LinkPickerList RequestsObj` (with a simple getter and setter).

Regarding your specific question, I'm not (directly) converting the JSON back to an instance of LinkPickerList, but that is done by the webapi model binder  I suppose.

I can even tell you that I've tested inserting the JSON directly in the database and the load is working well - meaning that I can retrieve that JSON string property from the database, deserialize it to a LinkPickerList, send it to the browser and the editor is working properly :)

Thanks!

**Comment by FDBenevides** [comment]
@abjerner I didn't notice that the LinkPickerItem's simple constructor was marked as `internal`. 

Decorating the constructor with the `[JsonConstructor]` attribute makes it work properly :)

**Comment by abjerner** [comment]
@FDBenevides The models dont represent the JSON 100%, so the JSON is parsed somewhat manually - also to handle a few different scenarios, legacy values and similar. For instance, the I'm using the static `LinkPickerList.Parse` method to create a new instance from an instance of `JObject`.

Using the `[JsonConstructor]` attribute will get you a long way to let you parse the model automatically, but it seems that the `url` property of each item won't be parsed properly - again because I have some extra logic going on inside the model.

I think the trick is to create a custom JSON converter, which I have done in this commit: https://github.com/skybrud/Skybrud.LinkPicker/commit/051fe7dafcb1c6498b6172767c3c09df04f58314

I will need to do some more testing before this will make it to a new release.  Meanwhile it should work if you copy the `LinkPickerConverter` class from the commit, and add a `[JsonConverter(typeof(LinkPickerConverter))]` attribute on the link picker list property in your own model.

**Comment by FDBenevides** [comment]
Hi @abjerner ,
I had tried with the JsonConverter implementation, but I think I forgot to decorate the classes with the attribute to specify the JsonConverter to be used... (silly me!!)

I'll try it again and let you know if it works.

Thanks ;)

**Comment by FDBenevides** [comment]
@abjerner it works :) 

Using the `[JsonConstructor]` , the Mode property would be wrong, because it would fallback to 'Url' even though it was a Content or Media link. So, the correct way is using the JsonConverter :+1: 

Thanks again ;)
